### ISSUE TITLE
how to open the injector

### ISSUE THREAD

**Issue by bluefyren** [R3nzTheCodeGOD/R3nzSkinTFT#10]
i dont know how to open the injector can u help me ?

**Comment by MiguLuz** [comment]
compile it with visual studio and ready

**Comment by bluefyren** [comment]
Yh but how to compile ?

**Comment by MiguLuz** [comment]
You open the visual studio and clone https://github.com/R3nzTheCodeGOD/R3nzSkinTFT.git then you have a button that says compile, just click and that's it

**Comment by bluefyren** [comment]
Ok thx for ur time

**Comment by bluefyren** [comment]
i dont have the button "compile" its normal ?

**Comment by R3nzTheCodeGOD** [comment]
### If you don't know what you're doing, why not use the pre-compiled version?

[Latest Version](https://github.com/R3nzTheCodeGOD/R3nzSkinTFT/releases/latest)
