### ISSUE TITLE
Update for the new skins

### ISSUE THREAD

**Issue by MiguLuz** [R3nzTheCodeGOD/R3nzSkinTFT#11]
how to update manually for the new skin

**Comment by MiguLuz** [comment]
From what it says it has auto update but it is not

**Comment by R3nzTheCodeGOD** [comment]
### New little legends added ( a69d613ebb9215e9e7516879b5e69e0393a73e43 )

`note:` **Auto update is for skins of little legends. Newly added little legends are not updated automatically.**
