### ISSUE TITLE
R3nzTFT Set 9 

### ISSUE THREAD

**Issue by Sentilz** [R3nzTheCodeGOD/R3nzSkinTFT#37]
R3nzTFT Skin changer doesn't working bc of this new set 9. 
I'll be happy when it could be fixed and updated, please. @R3nzTheCodeGOD

**Comment by rumi-chan** [comment]
> R3nzTFT Skin changer doesn't working bc of this new set 9. I'll be happy when it could be fixed and updated, please. @R3nzTheCodeGOD

You can try my updated version here
https://github.com/rumi-chan/Sakura
