### ISSUE TITLE
IT'S VIRUS ( Trojan:Script/Wacatac.H!ml )

### ISSUE THREAD

**Issue by FelpsAnaoRJ** [R3nzTheCodeGOD/R3nzSkinTFT#8]

**Comment by R3nzTheCodeGOD** [comment]
![pp](https://user-images.githubusercontent.com/58574988/188254788-33f295ab-2813-4d15-8a46-703f8ce298eb.png)

**Comment by R3nzTheCodeGOD** [comment]
Yes dude are you saying the open source project is a virus?

**Comment by seth007-moo** [comment]
> _No description provided._

lmao
